### ISSUE TITLE
Unused variable

### ISSUE THREAD

**Issue by meldwatts** [head-first-csharp/fourth-edition#12]
### In Sloppy Joe's Project (Chapter 04) there is an unused variable:

     `string guacamolePrice;`

It's declare at the beginning of the code Behind of the XAML window, then:

      `guacamolePrice = guacamoleMenuItem.Price`

And never get used.

Maybe in the next line your intent was to use `guacamolePrice` instead of guacamoleMenu.Price for the concatenation?:

     `guacamole.Text = "Add guacamole for " + guacamoleMenuItem.Price`

**Comment by andrewstellman** [comment]
Thanks so much for letting us know! Yes, you're absolutely right—I meant to use guacamolePrice for concatenation. The last line of code in the method should be:

`guacamole.Text = "Add guacamole for " + guacamolePrice;`

I included the extra variable because some readers are still getting used to the debugger, and I wanted to make it easy for them to see the price if they're debugging through the code.

I'll work with the O'Reilly production team to make sure they're removed from future printings and the digital editions. The update is live on the errata page now: https://www.oreilly.com/catalog/errata.csp?isbn=9781491976708
