### ISSUE TITLE
Match Game Error - 'Index was out of range'

### ISSUE THREAD

**Issue by jlaniertccd** [head-first-csharp/fourth-edition#13]
I believe I have everything correct (using Kindle version) and when trying to run it's kicking out this error:

System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')'

 private void SetUpGame()
        {
            List<string> animalEmoji = new List<string>()
            {
                "🐱‍","🐱‍",
                "🐴","🐴‍",
                "🐯","🐯‍",
                "🐔","🐔‍",
                "🙉","🙉‍",
                "🐼","🐼‍",
                "🦄","🦄‍",
                "🐍","🐍‍",
            };
            Random random = new Random();

            foreach (TextBlock textBlock in mainGrid.Children.OfType<TextBlock>())
            {
                int index = random.Next(animalEmoji.Count);
                string nextEmoji = animalEmoji[index];  //This is the line in which the error occurs
                textBlock.Text = nextEmoji;
                animalEmoji.RemoveAt(index);
            }
        }
    }

**Comment by andrewstellman** [comment]
Hi, and thanks for reading our book! 🙏 

An ArgumentOutOfRange exception is telling you that it ran out of emoji in the animalEmoji list but there's still a TextBlock to add an emoji to. This usually happens if there's accidentally an extra TextBlock in your XAML (which is easy to do accidentally with copy/paste). Can you check to see if there are exactly 16 <TextBlock> controls in your XAML grid?

Thanks,
Andrew

**Comment by jlaniertccd** [comment]
Thanks - that was it.
