### ISSUE TITLE
Chapter 1 code p 25 index out of range

### ISSUE THREAD

**Issue by lhwitherspoon** [head-first-csharp/fourth-edition#15]
Hi,

I am having trouble with the code in the WPF version of the MatchGame in Chapter 1.

The problem is with the code added on page 25 of the print edition. It's line 71 in the code on Github for that chapter. 

`string nextEmoji = animalEmoji[index]` throws an error: 
`"System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')'"`

I've been attempting to debug it. It appears that even though it fills in all the text blocks, it does not stop after completion and attempts to loop through one more time. If I comment on the last line of that block `(animalEmoji.RemoveAt(index);` it will complete without error, but there are three of one type of emoji and only one of another. 

Developing on Windows 10, whatever the latest update is (2020H?) Visual Studio 2019; targeting the latest .NET (5.X), which may mean it is using C# 9.

Probably needs a break condition, e.g. if animalEmoji.Count = 0 then break, but I am not sure how and when this is done in C#. 
Anyway, enjoying the book (the Mac Version of the project worked).

Thanks for the book and the help,

Les

**Comment by andrewstellman** [comment]
HI Les,

Thanks for getting in touch! Double-check that you have exactly 16 <TextBlock> controls in your XAML code, and exactly eight pairs of emoji. There's an explanation of of that problem here: https://github.com/head-first-csharp/fourth-edition/blob/master/README.md#did-you-run-into-trouble-with-the-project-in-the-first-chapter

Did that fix your problem? If not, let me know and I'm happy to help you troubleshoot (and then I can update the GitHub page with our solution to help other readers.)

Thanks,
Andrew

**Comment by lhwitherspoon** [comment]
Andrew,
Appreciate the speedy reply.  When I checked before writing I had 16 controls and eight pairs of emoji in the XAML, but I will take a look again & run through the solution you provided. I'll let you know either way. 
Thanks,
Les

**Comment by lhwitherspoon** [comment]
Okay, it was on my end & it is running. Thanks for the help.
