### ISSUE TITLE
Page 169, 4th Edition typo

### ISSUE THREAD

**Issue by chessboards** [head-first-csharp/fourth-edition#20]
Apologies if it's already been discovered, however I've found that on page 169, there's an error in the first paragraph:
"256 cast to a byte will have a value of 0, 25 will be converted to 1, 258 to 2, etc., up to 365, which will end up being 109."

which should be,

"256 cast to a byte will have a value of 0, 25`7` will be converted to 1, 258 to 2, etc., up to 365, which will end up being 109."

**Comment by andrewstellman** [comment]
Thanks! Yes, it turns out that someone did report that one, but Jenny and I both appreciate you taking the time to let us know about it anyway! 🙂

If you're curious, you can see all of the changes on the book's errata page: https://www.oreilly.com/catalog/errata.csp?isbn=9781491976708 – mostly small typos, nothing too huge (IMO), which is nice.
