### ISSUE TITLE
MainWindow 'no accessible extension method error

### ISSUE THREAD

**Issue by jtmcvay** [head-first-csharp/fourth-edition#57]
Hi, all. 

I have this error that is showing up and I can't seem to fix it. I've even copied the code and pasted it in and it still shows up. Any ideas?

_'MainWindow' does not contain a definition for the 'timeTextBlock_TextChanged' and no accessible extension method 'timeTextBlock_TextChanged' accepting a first argument of type 'MainWindow' could be found (are you missing a using directive or an assembly reference?)_

Help! Thanks!

JTMc

**Comment by andrewstellman** [comment]
Looks like you may have dragged a TextBox into your window instead of a TextBlock. Make sure that the XAML for your TimeTextBlock -- carefully compare the code in your IDE with the code in the book.

<img width="936" alt="image" src="https://github.com/head-first-csharp/fourth-edition/assets/7516297/8dd1eb23-5590-4725-a37a-3c2b953f7ae0">

**Comment by jtmcvay** [comment]
That was it! Thank you!

JTMc

**Comment by andrewstellman** [comment]
Yay, glad to help!!
