### ISSUE TITLE
p141 Class Diagrams

### ISSUE THREAD

**Issue by Delgathar** [head-first-csharp/fourth-edition#8]
Hello,  Wasn't sure where to leave a comment like this.

I've been looking over the pdf and it's definitely improved over version 3.  On page 141 you advise to use Class Diagrams.  But I was surprised you didn't mention the VS Class Designer.  I find this tool very useful because it generates code as I design the class but still gives me a visual reference how everything comes together.

This is a screenshot of me building TheQuest lab using the VS class diagram.  I had reached this lab when my computer died.  Because so many lessons reuse code and I didn't want to start over from scratch, I admit to ragequitting but I've slowly worked my way back to this lab again.  Reading the instructions in the pdf on Github is a godsend.  I don't have to worry about losing my work again.  Thank you for that.  Now I've got a lab to complete.
![Screenshot_1](https://user-images.githubusercontent.com/9401098/98332000-cfcbe380-1fcb-11eb-87a7-4618243a2575.jpg)

**Comment by andrewstellman** [comment]
That looks great! We actually thought about using the Visual Studio tools, but in the end we decided to stick with pencil and paper. 

The reason is that we need to be really careful about introducing new tools for our readers. While many of our readers already have experience with classes and object modeling (I'm guessing you do!), these are completely new concepts to a lot of our readers, and we're really careful not to overwhelm them. Drawing class diagrams on paper feels a lot friendlier for those folks, and helps them get up and running quickly.

I hope this helps explain why we made the decisions we did!

**Comment by Delgathar** [comment]
Actually it was your book that got me looking for a class diagram.  First I went to third party apps to make my own Class model and it was a pain getting them to match your book.  Then I found out there was one built into VS and started using that.  I do understand your reasoning though. Thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
